2025-07-06 21:49:00,538 - INFO - User Tony Stark logged in
2025-07-06 21:49:00,538 - ERROR - Error processing data: Invalid data
Traceback (most recent call last):
  File "e:\AIBootcamp\PythonTraining\4_python_advanced\9_logging\logging_2.py", line 18, in process_data
    raise ValueError("Invalid data")
ValueError: Invalid data
2025-07-06 21:49:00,546 - INFO - User Tony Stark logged out
2025-07-06 21:49:44,088 - INFO - User Tony Stark logged in
2025-07-06 21:49:44,088 - ERROR - Error processing data: Invalid data
Traceback (most recent call last):
  File "e:\AIBootcamp\PythonTraining\4_python_advanced\9_logging\logging_2.py", line 18, in process_data
    raise ValueError("Invalid data")
ValueError: Invalid data
2025-07-06 21:49:44,103 - INFO - User Tony Stark logged out
